---

- name: Trim Filesystem
  shell: fstrim -av

- name: Remove build dependencies
  action: apt pkg={{item}} state=removed
  with_items:
    - git
    - build-essential
    - autoconf
    - automake
    - pkg-config
    - python-setuptools
    - gcc
    - gcc-7
    - libtool
    - g++
    - g++-7
    - cpp
    - cpp-7
    - libgl1-mesa-dri
    - libllvm5.0
    - gnome-icon-theme
    - adwaita-icon-theme
    - libgtk-3-common
    - libgtk2.0-common
    - python-gt4
    - libqtgui4
    - libc6-dbg
    - python-matplotlib-data
    - "*-dev"
    - "x11-*"

- name: Cleanup Cruft files
  action: file state=absent path={{item}}
  with_items:
    - "/var/cache/apt/"
    - "/var/cache/debconf/"
    - "/var/lib/mysql/"
    - "/var/lib/apt/"
    - "/var/log/"
    - "/usr/share/doc/"
    - "/usr/share/icons/"


